server:
  port: 9090
spring:
  messages:
    encoding: UTF-8
  datasource:
    druid:
#      url: jdbc:mysql://8.134.88.217:3306/nftmarket?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&serverTimezone=Asia/Shanghai
      url: jdbc:mysql://127.0.0.1:3306/nftdemo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
#      password: 6822jtBEjWfZkdDB
      password: admin
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      filters: stat,wall
  data:
    mongodb:
      host: 47.243.48.92
      port: 27017
      database: test


  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#logging:
#  config: classpath:logback-spring.xml

